# Generated by Django 3.2.6 on 2021-08-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='globalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Tropical Deliveries', max_length=200)),
                ('year', models.CharField(default='2021', max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
